### ISSUE TITLE
Add back support to compile clip for OS X 10.7 platform

### ISSUE THREAD

**Issue by dacap** [dacap/clip#19]
If we run:

    cmake clip-source-dir \
      -G Ninja \
      -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7 \
      -DCMAKE_OSX_ARCHITECTURES=x86_64

Or `-DCMAKE_OSX_DEPLOYMENT_TARGET=10.8`, we will get a compilation error because it will use an old version of libc++ without `std::unique_ptr` (I guess an old version of the GNU libstdc++). This problem disappear if we use the 10.9 SDK.

This problem was introduced in da1f4bbb7744f910347b445bace0e4d931abd649
