### ISSUE TITLE
Does not compile on Linux (g++ 7.3.1)

### ISSUE THREAD

**Issue by bharadwaj-raju** [dacap/clip#11]
Compiling (either using the provided `CMakeLists` or a custom `g++` command), fails with this error.

Searching about the first error (the `std::function<bool()>` one) suggests that it is because `g++` is set to an old standard, but that is not the case here, since the same error is thrown with `-std=c++11`, `-std=c++14` and `-std=c++17`.

```cpp
/home/user/test/lib/clip/clip_x11.cpp:55:16: error: ‘function’ in namespace ‘std’ does not name a template type
   typedef std::function<bool()> notify_callback;
                ^~~~~~~~
/home/user/test/lib/clip/clip_x11.cpp:557:44: error: ‘notify_callback’ does not name a type
                                      const notify_callback&& callback) const {
                                            ^~~~~~~~~~~~~~~
/home/user/test/lib/clip/clip_x11.cpp:798:11: error: ‘notify_callback’ does not name a type
   mutable notify_callback m_callback;
           ^~~~~~~~~~~~~~~
/home/user/test/lib/clip/clip_x11.cpp: In member function ‘bool clip::{anonymous}::Manager::is_convertible(clip::format) const’:
/home/user/test/lib/clip/clip_x11.cpp:151:12: error: no matching function for call to ‘clip::{anonymous}::Manager::get_data_from_selection_owner(<brace-enclosed initializer list>, clip::{anonymous}::Manager::is_convertible(clip::format) const::<lambda()>) const’
           });
            ^
/home/user/test/lib/clip/clip_x11.cpp:556:8: note: candidate: bool clip::{anonymous}::Manager::get_data_from_selection_owner(const atoms&, const int&&) const
   bool get_data_from_selection_owner(const atoms& atoms,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/test/lib/clip/clip_x11.cpp:556:8: note:   no known conversion for argument 2 from ‘clip::{anonymous}::Manager::is_convertible(clip::format) const::<lambda()>’ to ‘const int&&’
/home/user/test/lib/clip/clip_x11.cpp: In member function ‘bool clip::{anonymous}::Manager::get_data(clip::format, char*, size_t) const’:
/home/user/test/lib/clip/clip_x11.cpp:212:14: error: no matching function for call to ‘clip::{anonymous}::Manager::get_data_from_selection_owner(const atoms&, clip::{anonymous}::Manager::get_data(clip::format, char*, size_t) const::<lambda()>) const’
             })) {
              ^
/home/user/test/lib/clip/clip_x11.cpp:556:8: note: candidate: bool clip::{anonymous}::Manager::get_data_from_selection_owner(const atoms&, const int&&) const
   bool get_data_from_selection_owner(const atoms& atoms,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/test/lib/clip/clip_x11.cpp:556:8: note:   no known conversion for argument 2 from ‘clip::{anonymous}::Manager::get_data(clip::format, char*, size_t) const::<lambda()>’ to ‘const int&&’
/home/user/test/lib/clip/clip_x11.cpp: In member function ‘size_t clip::{anonymous}::Manager::get_data_length(clip::format) const’:
/home/user/test/lib/clip/clip_x11.cpp:238:14: error: no matching function for call to ‘clip::{anonymous}::Manager::get_data_from_selection_owner(const atoms&, clip::{anonymous}::Manager::get_data_length(clip::format) const::<lambda()>) const’
             })) {
              ^
/home/user/test/lib/clip/clip_x11.cpp:556:8: note: candidate: bool clip::{anonymous}::Manager::get_data_from_selection_owner(const atoms&, const int&&) const
   bool get_data_from_selection_owner(const atoms& atoms,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/test/lib/clip/clip_x11.cpp:556:8: note:   no known conversion for argument 2 from ‘clip::{anonymous}::Manager::get_data_length(clip::format) const::<lambda()>’ to ‘const int&&’
/home/user/test/lib/clip/clip_x11.cpp: In member function ‘bool clip::{anonymous}::Manager::get_image(clip::image&) const’:
/home/user/test/lib/clip/clip_x11.cpp:274:12: error: no matching function for call to ‘clip::{anonymous}::Manager::get_data_from_selection_owner(<brace-enclosed initializer list>, clip::{anonymous}::Manager::get_image(clip::image&) const::<lambda()>) const’
           })) {
            ^
/home/user/test/lib/clip/clip_x11.cpp:556:8: note: candidate: bool clip::{anonymous}::Manager::get_data_from_selection_owner(const atoms&, const int&&) const
   bool get_data_from_selection_owner(const atoms& atoms,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/test/lib/clip/clip_x11.cpp:556:8: note:   no known conversion for argument 2 from ‘clip::{anonymous}::Manager::get_image(clip::image&) const::<lambda()>’ to ‘const int&&’
/home/user/test/lib/clip/clip_x11.cpp: In member function ‘bool clip::{anonymous}::Manager::get_image_spec(clip::image_spec&) const’:
/home/user/test/lib/clip/clip_x11.cpp:291:12: error: no matching function for call to ‘clip::{anonymous}::Manager::get_data_from_selection_owner(<brace-enclosed initializer list>, clip::{anonymous}::Manager::get_image_spec(clip::image_spec&) const::<lambda()>) const’
           })) {
            ^
/home/user/test/lib/clip/clip_x11.cpp:556:8: note: candidate: bool clip::{anonymous}::Manager::get_data_from_selection_owner(const atoms&, const int&&) const
   bool get_data_from_selection_owner(const atoms& atoms,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/test/lib/clip/clip_x11.cpp:556:8: note:   no known conversion for argument 2 from ‘clip::{anonymous}::Manager::get_image_spec(clip::image_spec&) const::<lambda()>’ to ‘const int&&’
/home/user/test/lib/clip/clip_x11.cpp: In member function ‘void clip::{anonymous}::Manager::call_callback(xcb_get_property_reply_t*)’:
/home/user/test/lib/clip/clip_x11.cpp:548:9: error: ‘m_callback’ was not declared in this scope
     if (m_callback)
         ^~~~~~~~~~
/home/user/test/lib/clip/clip_x11.cpp:548:9: note: suggested alternative: ‘call_callback’
     if (m_callback)
         ^~~~~~~~~~
         call_callback
/home/user/test/lib/clip/clip_x11.cpp: In member function ‘bool clip::{anonymous}::Manager::get_data_from_selection_owner(const atoms&, const int&&) const’:
/home/user/test/lib/clip/clip_x11.cpp:560:5: error: ‘m_callback’ was not declared in this scope
     m_callback = std::move(callback);
     ^~~~~~~~~~
/home/user/test/lib/clip/clip_x11.cpp:560:5: note: suggested alternative: ‘callback’
     m_callback = std::move(callback);
     ^~~~~~~~~~
     callback
/home/user/test/lib/clip/clip_x11.cpp:596:18: error: ‘notify_callback’ was not declared in this scope
     m_callback = notify_callback();
                  ^~~~~~~~~~~~~~~
/home/user/test/lib/clip/clip_x11.cpp:596:18: note: suggested alternative: ‘call_callback’
     m_callback = notify_callback();
                  ^~~~~~~~~~~~~~~
                  call_callback

```

**Comment by dacap** [comment]
[Testing gcc 7 on travis](https://travis-ci.org/dacap/clip/builds/384079920) and yeah, and I reproduced this compilation error. I'll try to fix it right now.

**Comment by bharadwaj-raju** [comment]
Can comfirm fixed. Thanks a lot!
