### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by yahyaemb** [dacap/clip#80]
Hi clip

I encountered an issue during the build process: "**ImpersonateAnonymousToken' was not declared in this scope...**" which made me wonder if it could be from the version of my compiler.

which compiler/version do you use?  
For me I use : **c++.exe (MinGW.org GCC-6.3.0-1) 6.3.0**  

Thanks in advance?

**Comment by yahyaemb** [comment]
I tried to compile with the latest version **14.2.0** and it worked!
